export default {
  login: 'pavankumar130',
  id: 122618703,
  node_id: 'U_kgDOB08DTw',
  avatar_url: 'https://avatars.githubusercontent.com/u/122618703?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/pavankumar130',
  html_url: 'https://github.com/pavankumar130',
  followers_url: 'https://api.github.com/users/pavankumar130/followers',
  following_url:
    'https://api.github.com/users/pavankumar130/following{/other_user}',
  gists_url: 'https://api.github.com/users/pavankumar130/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/pavankumar130/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/pavankumar130/subscriptions',
  organizations_url: 'https://api.github.com/users/pavankumar130/orgs',
  repos_url: 'https://api.github.com/users/pavankumar130/repos',
  events_url: 'https://api.github.com/users/pavankumar130/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/pavankumar130/received_events',
  type: 'User',
  site_admin: false,
  name: 'meravath pavan kumar',
  company: null,
  blog: '',
  location: 'Hyderabad,Telangana',
  email: null,
  hireable: true,
  bio: 'Studying CS at PDPD IIITDM Jabalpur. Passionate MERN full-stack developer. Proficient in MongoDB, Express.js, React.js, and Node.js. ',
  twitter_username: 'M_PAVAN_130',
  public_repos: 20,
  public_gists: 0,
  followers: 1,
  following: 15,
  created_at: '2023-01-13T13:46:23Z',
  updated_at: '2023-06-22T08:22:47Z',
}
