export default [
  {
    login: 'SasankBVM',
    id: 84608186,
    node_id: 'MDQ6VXNlcjg0NjA4MTg2',
    avatar_url: 'https://avatars.githubusercontent.com/u/84608186?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SasankBVM',
    html_url: 'https://github.com/SasankBVM',
    followers_url: 'https://api.github.com/users/SasankBVM/followers',
    following_url:
      'https://api.github.com/users/SasankBVM/following{/other_user}',
    gists_url: 'https://api.github.com/users/SasankBVM/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/SasankBVM/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/SasankBVM/subscriptions',
    organizations_url: 'https://api.github.com/users/SasankBVM/orgs',
    repos_url: 'https://api.github.com/users/SasankBVM/repos',
    events_url: 'https://api.github.com/users/SasankBVM/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/SasankBVM/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kokkiralaabhinav',
    id: 108206047,
    node_id: 'U_kgDOBnMX3w',
    avatar_url: 'https://avatars.githubusercontent.com/u/108206047?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kokkiralaabhinav',
    html_url: 'https://github.com/kokkiralaabhinav',
    followers_url: 'https://api.github.com/users/kokkiralaabhinav/followers',
    following_url:
      'https://api.github.com/users/kokkiralaabhinav/following{/other_user}',
    gists_url: 'https://api.github.com/users/kokkiralaabhinav/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/kokkiralaabhinav/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/kokkiralaabhinav/subscriptions',
    organizations_url: 'https://api.github.com/users/kokkiralaabhinav/orgs',
    repos_url: 'https://api.github.com/users/kokkiralaabhinav/repos',
    events_url:
      'https://api.github.com/users/kokkiralaabhinav/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kokkiralaabhinav/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'shivamsouravjha',
    id: 60891544,
    node_id: 'MDQ6VXNlcjYwODkxNTQ0',
    avatar_url: 'https://avatars.githubusercontent.com/u/60891544?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/shivamsouravjha',
    html_url: 'https://github.com/shivamsouravjha',
    followers_url: 'https://api.github.com/users/shivamsouravjha/followers',
    following_url:
      'https://api.github.com/users/shivamsouravjha/following{/other_user}',
    gists_url: 'https://api.github.com/users/shivamsouravjha/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/shivamsouravjha/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/shivamsouravjha/subscriptions',
    organizations_url: 'https://api.github.com/users/shivamsouravjha/orgs',
    repos_url: 'https://api.github.com/users/shivamsouravjha/repos',
    events_url: 'https://api.github.com/users/shivamsouravjha/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/shivamsouravjha/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Aksh-Bansal-dev',
    id: 63552235,
    node_id: 'MDQ6VXNlcjYzNTUyMjM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/63552235?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Aksh-Bansal-dev',
    html_url: 'https://github.com/Aksh-Bansal-dev',
    followers_url: 'https://api.github.com/users/Aksh-Bansal-dev/followers',
    following_url:
      'https://api.github.com/users/Aksh-Bansal-dev/following{/other_user}',
    gists_url: 'https://api.github.com/users/Aksh-Bansal-dev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Aksh-Bansal-dev/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Aksh-Bansal-dev/subscriptions',
    organizations_url: 'https://api.github.com/users/Aksh-Bansal-dev/orgs',
    repos_url: 'https://api.github.com/users/Aksh-Bansal-dev/repos',
    events_url: 'https://api.github.com/users/Aksh-Bansal-dev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Aksh-Bansal-dev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'somya51p',
    id: 64978837,
    node_id: 'MDQ6VXNlcjY0OTc4ODM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/64978837?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/somya51p',
    html_url: 'https://github.com/somya51p',
    followers_url: 'https://api.github.com/users/somya51p/followers',
    following_url:
      'https://api.github.com/users/somya51p/following{/other_user}',
    gists_url: 'https://api.github.com/users/somya51p/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/somya51p/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/somya51p/subscriptions',
    organizations_url: 'https://api.github.com/users/somya51p/orgs',
    repos_url: 'https://api.github.com/users/somya51p/repos',
    events_url: 'https://api.github.com/users/somya51p/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/somya51p/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'brijsiyag',
    id: 71015892,
    node_id: 'MDQ6VXNlcjcxMDE1ODky',
    avatar_url: 'https://avatars.githubusercontent.com/u/71015892?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/brijsiyag',
    html_url: 'https://github.com/brijsiyag',
    followers_url: 'https://api.github.com/users/brijsiyag/followers',
    following_url:
      'https://api.github.com/users/brijsiyag/following{/other_user}',
    gists_url: 'https://api.github.com/users/brijsiyag/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/brijsiyag/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/brijsiyag/subscriptions',
    organizations_url: 'https://api.github.com/users/brijsiyag/orgs',
    repos_url: 'https://api.github.com/users/brijsiyag/repos',
    events_url: 'https://api.github.com/users/brijsiyag/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/brijsiyag/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Ayushsunny',
    id: 73520373,
    node_id: 'MDQ6VXNlcjczNTIwMzcz',
    avatar_url: 'https://avatars.githubusercontent.com/u/73520373?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Ayushsunny',
    html_url: 'https://github.com/Ayushsunny',
    followers_url: 'https://api.github.com/users/Ayushsunny/followers',
    following_url:
      'https://api.github.com/users/Ayushsunny/following{/other_user}',
    gists_url: 'https://api.github.com/users/Ayushsunny/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Ayushsunny/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Ayushsunny/subscriptions',
    organizations_url: 'https://api.github.com/users/Ayushsunny/orgs',
    repos_url: 'https://api.github.com/users/Ayushsunny/repos',
    events_url: 'https://api.github.com/users/Ayushsunny/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Ayushsunny/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'yuvraj-singh08',
    id: 77259029,
    node_id: 'MDQ6VXNlcjc3MjU5MDI5',
    avatar_url: 'https://avatars.githubusercontent.com/u/77259029?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/yuvraj-singh08',
    html_url: 'https://github.com/yuvraj-singh08',
    followers_url: 'https://api.github.com/users/yuvraj-singh08/followers',
    following_url:
      'https://api.github.com/users/yuvraj-singh08/following{/other_user}',
    gists_url: 'https://api.github.com/users/yuvraj-singh08/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/yuvraj-singh08/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/yuvraj-singh08/subscriptions',
    organizations_url: 'https://api.github.com/users/yuvraj-singh08/orgs',
    repos_url: 'https://api.github.com/users/yuvraj-singh08/repos',
    events_url: 'https://api.github.com/users/yuvraj-singh08/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/yuvraj-singh08/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ArnabMdev',
    id: 78680046,
    node_id: 'MDQ6VXNlcjc4NjgwMDQ2',
    avatar_url: 'https://avatars.githubusercontent.com/u/78680046?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ArnabMdev',
    html_url: 'https://github.com/ArnabMdev',
    followers_url: 'https://api.github.com/users/ArnabMdev/followers',
    following_url:
      'https://api.github.com/users/ArnabMdev/following{/other_user}',
    gists_url: 'https://api.github.com/users/ArnabMdev/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ArnabMdev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ArnabMdev/subscriptions',
    organizations_url: 'https://api.github.com/users/ArnabMdev/orgs',
    repos_url: 'https://api.github.com/users/ArnabMdev/repos',
    events_url: 'https://api.github.com/users/ArnabMdev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ArnabMdev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'artizticamit',
    id: 78965821,
    node_id: 'MDQ6VXNlcjc4OTY1ODIx',
    avatar_url: 'https://avatars.githubusercontent.com/u/78965821?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/artizticamit',
    html_url: 'https://github.com/artizticamit',
    followers_url: 'https://api.github.com/users/artizticamit/followers',
    following_url:
      'https://api.github.com/users/artizticamit/following{/other_user}',
    gists_url: 'https://api.github.com/users/artizticamit/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/artizticamit/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/artizticamit/subscriptions',
    organizations_url: 'https://api.github.com/users/artizticamit/orgs',
    repos_url: 'https://api.github.com/users/artizticamit/repos',
    events_url: 'https://api.github.com/users/artizticamit/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/artizticamit/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Param-987',
    id: 79018889,
    node_id: 'MDQ6VXNlcjc5MDE4ODg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/79018889?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Param-987',
    html_url: 'https://github.com/Param-987',
    followers_url: 'https://api.github.com/users/Param-987/followers',
    following_url:
      'https://api.github.com/users/Param-987/following{/other_user}',
    gists_url: 'https://api.github.com/users/Param-987/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Param-987/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Param-987/subscriptions',
    organizations_url: 'https://api.github.com/users/Param-987/orgs',
    repos_url: 'https://api.github.com/users/Param-987/repos',
    events_url: 'https://api.github.com/users/Param-987/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Param-987/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Aabhas0806',
    id: 80005529,
    node_id: 'MDQ6VXNlcjgwMDA1NTI5',
    avatar_url: 'https://avatars.githubusercontent.com/u/80005529?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Aabhas0806',
    html_url: 'https://github.com/Aabhas0806',
    followers_url: 'https://api.github.com/users/Aabhas0806/followers',
    following_url:
      'https://api.github.com/users/Aabhas0806/following{/other_user}',
    gists_url: 'https://api.github.com/users/Aabhas0806/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Aabhas0806/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Aabhas0806/subscriptions',
    organizations_url: 'https://api.github.com/users/Aabhas0806/orgs',
    repos_url: 'https://api.github.com/users/Aabhas0806/repos',
    events_url: 'https://api.github.com/users/Aabhas0806/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Aabhas0806/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'optimm',
    id: 81467507,
    node_id: 'MDQ6VXNlcjgxNDY3NTA3',
    avatar_url: 'https://avatars.githubusercontent.com/u/81467507?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/optimm',
    html_url: 'https://github.com/optimm',
    followers_url: 'https://api.github.com/users/optimm/followers',
    following_url: 'https://api.github.com/users/optimm/following{/other_user}',
    gists_url: 'https://api.github.com/users/optimm/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/optimm/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/optimm/subscriptions',
    organizations_url: 'https://api.github.com/users/optimm/orgs',
    repos_url: 'https://api.github.com/users/optimm/repos',
    events_url: 'https://api.github.com/users/optimm/events{/privacy}',
    received_events_url: 'https://api.github.com/users/optimm/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'raghavpatidar',
    id: 85017995,
    node_id: 'MDQ6VXNlcjg1MDE3OTk1',
    avatar_url: 'https://avatars.githubusercontent.com/u/85017995?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/raghavpatidar',
    html_url: 'https://github.com/raghavpatidar',
    followers_url: 'https://api.github.com/users/raghavpatidar/followers',
    following_url:
      'https://api.github.com/users/raghavpatidar/following{/other_user}',
    gists_url: 'https://api.github.com/users/raghavpatidar/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/raghavpatidar/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/raghavpatidar/subscriptions',
    organizations_url: 'https://api.github.com/users/raghavpatidar/orgs',
    repos_url: 'https://api.github.com/users/raghavpatidar/repos',
    events_url: 'https://api.github.com/users/raghavpatidar/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/raghavpatidar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'aparna-bhatt',
    id: 86338542,
    node_id: 'MDQ6VXNlcjg2MzM4NTQy',
    avatar_url: 'https://avatars.githubusercontent.com/u/86338542?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/aparna-bhatt',
    html_url: 'https://github.com/aparna-bhatt',
    followers_url: 'https://api.github.com/users/aparna-bhatt/followers',
    following_url:
      'https://api.github.com/users/aparna-bhatt/following{/other_user}',
    gists_url: 'https://api.github.com/users/aparna-bhatt/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/aparna-bhatt/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/aparna-bhatt/subscriptions',
    organizations_url: 'https://api.github.com/users/aparna-bhatt/orgs',
    repos_url: 'https://api.github.com/users/aparna-bhatt/repos',
    events_url: 'https://api.github.com/users/aparna-bhatt/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/aparna-bhatt/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ShivamJhaa',
    id: 86483059,
    node_id: 'MDQ6VXNlcjg2NDgzMDU5',
    avatar_url: 'https://avatars.githubusercontent.com/u/86483059?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ShivamJhaa',
    html_url: 'https://github.com/ShivamJhaa',
    followers_url: 'https://api.github.com/users/ShivamJhaa/followers',
    following_url:
      'https://api.github.com/users/ShivamJhaa/following{/other_user}',
    gists_url: 'https://api.github.com/users/ShivamJhaa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ShivamJhaa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ShivamJhaa/subscriptions',
    organizations_url: 'https://api.github.com/users/ShivamJhaa/orgs',
    repos_url: 'https://api.github.com/users/ShivamJhaa/repos',
    events_url: 'https://api.github.com/users/ShivamJhaa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ShivamJhaa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mayankjx',
    id: 88933829,
    node_id: 'MDQ6VXNlcjg4OTMzODI5',
    avatar_url: 'https://avatars.githubusercontent.com/u/88933829?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mayankjx',
    html_url: 'https://github.com/mayankjx',
    followers_url: 'https://api.github.com/users/mayankjx/followers',
    following_url:
      'https://api.github.com/users/mayankjx/following{/other_user}',
    gists_url: 'https://api.github.com/users/mayankjx/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mayankjx/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mayankjx/subscriptions',
    organizations_url: 'https://api.github.com/users/mayankjx/orgs',
    repos_url: 'https://api.github.com/users/mayankjx/repos',
    events_url: 'https://api.github.com/users/mayankjx/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mayankjx/received_events',
    type: 'User',
    site_admin: false,
  },
]
